on:
  pull_request:
    branches:
      - 'develop'
jobs:
  pr:
    name: "Pull Request Checks"
    runs-on: ubuntu-latest
    # Don't run if this is a change set created by the Release Bot
    if: "!contains(github.event.head_commit.author.name, 'Release Bot')"
    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Cache .m2
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    - name: Prepare mvnw
      run: chmod +x ./mvnw

    - name: Build
      run: ./mvnw clean verify -B
  empty-job:
    # If no jobs run, github action considers it a test failure – which seems like a bug
    # this makes it so the top-level if statement for the job does not give status failure.
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.author.name, 'Release Bot')"
    steps:
      - name: Mark AS Success
        run: |
          echo "This job will always succeed. If no jobs run, we still want the workflow to give status success."