on:
  push:
    branches:
      - develop
    tags-ignore:
      - '**' # Don't trigger on tags being pushed
jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.author.name, 'Release Bot')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_RELEASE_TOKEN }}

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache .m2
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Prepare mvnw
        run: chmod +x ./mvnw

      - name: Configure git
        run: |
          git config --global committer.email "noreply@github.com"
          git config --global committer.name "Release Bot"
          git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global author.name "Release Bot"

      - name: Prepare release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./mvnw --batch-mode release:prepare -Dusername=$GITHUB_ACTOR -Dpassword=$GITHUB_TOKEN

      - name: Perform release and Deploy a new version
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: ./mvnw clean release:perform -B -Ddocker.username=$DOCKER_HUB_USERNAME -Ddocker.password=$DOCKER_HUB_PASSWORD
